import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import BottomControll from "./components/BottomControll";
import FooterComp from "./components/FooterComp";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative h-[100%]`}>
        <Header/>
        {children}
         {/* <BottomControll/>? */}
         {/* <FooterComp/> */}
      </body>
    </html>
  );
}
